# Use official Nginx image
FROM nginx:alpine

# Copy custom index.html to Nginx default html folder
COPY index.html /usr/share/nginx/html/index.html

# Copy any JS/CSS if you add later
# COPY ./static /usr/share/nginx/html/static

EXPOSE 80
