apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3tierapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/nadzzdan/3tierapp.git"
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true