apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>3-Tier App</title></head>
    <body>
      <h2>Submit Text</h2>
      <form id="textForm">
        <input type="text" id="userText" required />
        <button type="submit">Submit</button>
      </form>
      <h3>Stored Texts:</h3>
      <ul id="textList"></ul>
      <script>
        const apiUrl = "/api"; // will route via Ingress
        document.getElementById("textForm").addEventListener("submit", async (e) => {
          e.preventDefault();
          const text = document.getElementById("userText").value;
          await fetch(`${apiUrl}/submit`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ text })
          });
          loadTexts();
        });
        async function loadTexts() {
          const res = await fetch(`${apiUrl}/texts`);
          const data = await res.json();
          const list = document.getElementById("textList");
          list.innerHTML = "";
          data.forEach(t => {
            const li = document.createElement("li");
            li.textContent = t;
            list.appendChild(li);
          });
        }
        loadTexts();
      </script>
    </body>
    </html>
