apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels: { app: postgres }
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - { name: POSTGRES_DB, value: "mydb" }
        - { name: POSTGRES_USER, value: "myuser" }
        - { name: POSTGRES_PASSWORD, value: "mypassword" }
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: data
        emptyDir: {}
      - name: init-sql
        configMap:
          name: postgres-init-sql
