apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        timestamp: "2024-12-19T12:00:00Z"
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z prod-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: backend
          image: ghcr.io/nadzzdan/backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"