name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/3tierapp-backend:latest
            ghcr.io/${{ github.repository_owner }}/3tierapp-backend:${{ github.ref_name }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/3tierapp-frontend:latest
            ghcr.io/${{ github.repository_owner }}/3tierapp-frontend:${{ github.ref_name }}

      - name: Build and Push Database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/3tierapp-database:latest
            ghcr.io/${{ github.repository_owner }}/3tierapp-database:${{ github.ref_name }}
