name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend:latest
            ghcr.io/${{ github.repository_owner }}/backend:${{ github.ref_name }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/frontend:latest
            ghcr.io/${{ github.repository_owner }}/frontend:${{ github.ref_name }}

      - name: Build and Push Database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/database:latest
            ghcr.io/${{ github.repository_owner }}/database:${{ github.ref_name }}

      - name: Update Kustomize image tags
        run: |
          echo "Current tag: ${{ github.ref_name }}"
          
          # Switch to main branch
          git checkout main
          git pull origin main
          
          cd k8s/overlays/production
          
          # Show current content
          echo "Current kustomization.yaml content:"
          cat kustomization.yaml
          
          # Update the tags
          sed -i "s/newTag: latest/newTag: ${{ github.ref_name }}/g" kustomization.yaml
          
          # Show updated content
          echo "Updated kustomization.yaml content:"
          cat kustomization.yaml
          
          # Check if there are changes
          if git diff --quiet kustomization.yaml; then
            echo "No changes detected in kustomization.yaml"
          else
            echo "Changes detected, committing..."
            # Commit and push the changes
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add kustomization.yaml
            git commit -m "Update image tags to ${{ github.ref_name }}"
            git push origin main
          fi