name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/3tierapp-backend:latest
            ghcr.io/${{ github.repository_owner }}/3tierapp-backend:v1

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/3tierapp-frontend:latest
            ghcr.io/${{ github.repository_owner }}/3tierapp-frontend:v1

      - name: Build and Push Database
        uses: docker/build-push-action@v4
        with:
          context: ./database
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/3tierapp-database:latest
            ghcr.io/${{ github.repository_owner }}/3tierapp-database:v1
