name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/3tierapp-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/3tierapp-backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/3tierapp-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/3tierapp-frontend:latest
