name: Build and Deploy 3-Tier App

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-alpha'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          file: ./backend/Dockerfile
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          file: ./frontend/Dockerfile
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}

      - name: Deploy to Kubernetes
        run: |
          # Update deployment images
          sed -i "s|ghcr.io/nadzzdan/3tierapp/backend:latest|ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}|g" k8s/backend/backend-deployment.yaml
          sed -i "s|ghcr.io/nadzzdan/3tierapp/frontend:latest|ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}|g" k8s/frontend/frontend-deployment.yaml
          
          # Deploy to Kubernetes
          kubectl apply -f k8s/postgres/
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/ingress.yaml
          
          # Wait for rollout
          kubectl rollout status deployment/backend -n three-tier-prod --timeout=300s
          kubectl rollout status deployment/frontend -n three-tier-prod --timeout=300s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}